# exclude .github directory, the .pr-commit-config.yaml file
exclude: ^(.github/.*|.pre-commit-config.yaml)$
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: env-check
        name: environment sync
        entry: poetry install --sync
        language: system
        pass_filenames: false
      - id: check
        name: check
        entry: poe lint
        language: system
        pass_filenames: false
        types_or: [python]